struct sensor_types_codes {
	char type[64];
	uint8_t type_code;
	uint8_t specific_offset;
	char event_descrip[128];
	uint8_t event_data_2_flag;
	uint8_t event_data_3_flag;
	uint8_t event_data_2;
	char event_data_2_descrip[64];
	uint8_t event_data_3;
	char event_data_3_descrip[64];
};

struct types_codes g_types_codes_table = {
	{.type = "reserved", .type_code = 0x0, .specific_offset=0, .event_descrip = "reserved", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Temperature", .type_code = 0x1, .specific_offset=0, .event_descrip = "Temperature", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Voltage", .type_code = 0x2, .specific_offset=0, .event_descrip = "Voltage", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Current", .type_code = 0x3, .specific_offset=0, .event_descrip = "Current", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Fan", .type_code = 0x4, .specific_offset=0, .event_descrip = "Fan", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x0, .event_descrip = "General Chassis Intrusion", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x1, .event_descrip = "Drive Bay Intrusion", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x2, .event_descrip = "I/O Card Area Intrusion", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x3, .event_descrip = "Processor area Intrusion", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x4, .event_descrip = "LAN Leash Lost", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x5, .event_descrip = "Unauthoorized dock", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Physical Security", .type_code = 0x5, .specific_offset=0x6, .event_descrip = "Fan area intrusion", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Platform Security Violation Attempt", .type_code = 0x6, .specific_offset=0x0, .event_descrip = "Secure Mode (Front Panel Lockout) Violation Attempt", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Security Violation Attempt", .type_code = 0x6, .specific_offset=0x1, .event_descrip = "Pre-boot Password Violation - user password", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Security Violation Attempt", .type_code = 0x6, .specific_offset=0x2, .event_descrip = "Pre-boot Password Violation attempt - setup password", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Security Violation Attempt", .type_code = 0x6, .specific_offset=0x3, .event_descrip = "Pre-boot Password Violation - network boot password", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Security Violation Attempt", .type_code = 0x6, .specific_offset=0x4, .event_descrip = "Other pre-boot Password Violation", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Security Violation Attempt", .type_code = 0x6, .specific_offset=0x5, .event_descrip = "Out-of-band Access Password Violation", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x0, .event_descrip = "IERR", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x1, .event_descrip = "Thermal Trip", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x2, .event_descrip = "FRB1/BIST Failure", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x3, .event_descrip = "FRB2/Hang in POST Failure", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x4, .event_descrip = "FRB3/Processor Startup/Initialization Failure (CPU didn't start)", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x5, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x6, .event_descrip = "SM BIOS 'Uncorrectable CPU-Complex Error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x7, .event_descrip = "Processor Presence Detected", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x8, .event_descrip = "Processor disabled", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0x9, .event_descrip = "Terminator Presence Detected", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0xA, .event_descrip = "Processor Automatically Throttled", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0xB, .event_descrip = "Machine Check Exception (Uncorrectable)", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Processor", .type_code = 0x7, .specific_offset=0xC, .event_descrip = "Correctable Machine Check Error", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x0, .event_descrip = "Presence Detected", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x1, .event_descrip = "Power Supply Failure detected", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x2, .event_descrip = "Predictive Failure", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x3, .event_descrip = "Power Supply input lost (AC/DC)", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x4, .event_descrip = "Power Supply input lost or out-of-range", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x5, .event_descrip = "Power Supply input out-of-range, but present", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x6, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=1, .event_data_3=0, .event_data_3_descrip="Vendor Mismatch"},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x6, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=1, .event_data_3=1, .event_data_3_descrip="Revision Mismatch"},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x6, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=1, .event_data_3=2, .event_data_3_descrip="Processor Missing"},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x6, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=1, .event_data_3=3, .event_data_3_descrip="Power Supply Rating Mismatch"},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x6, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=1, .event_data_3=4, .event_data_3_descrip="Voltage Rating Mismatch"},
	{.type = "Power Supply & VRM", .type_code = 0x8, .specific_offset=0x7, .event_descrip = "Power Supply Inactive", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x0, .event_descrip = "Power Off/Power Down", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x1, .event_descrip = "Power Cycle", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x2, .event_descrip = "240 KVA Power Down", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x3, .event_descrip = "Interlock Power Down", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x4, .event_descrip = "AC Lost / Power Input Lost", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x5, .event_descrip = "Soft Power Control Failure", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x6, .event_descrip = "Power Unit Failure Detected", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Power Unit", .type_code = 0x9, .specific_offset=0x7, .event_descrip = "Predictive Failure", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Cooling Device", .type_code = 0xA, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Other Units-based Sensor", .type_code = 0xB, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x0, .event_descrip = "Correctable ECC/other correctable memory error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x1, .event_descrip = "UnCorrectable ECC/other uncorrectable memory error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x2, .event_descrip = "Parity", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x3, .event_descrip = "Memory Scrub Failed (stuck bit)", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x4, .event_descrip = "Memory Device Disabled", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x5, .event_descrip = "Correctable ECC / other correctable memory error logging limit reached", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x6, .event_descrip = "Presence detected", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x7, .event_descrip = "Configuration Error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x8, .event_descrip = "Spare", .event_data_2_flag=0, .event_data_3_flag=1, .event_data_3_descrp = "Memory Module/device identification"},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0x9, .event_descrip = "Memory Automatically Throttled", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Memory", .type_code = 0xC, .specific_offset=0xA, .event_descrip = "Critical Temperature", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x0, .event_descrip = "Drive Presence", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x1, .event_descrip = "Drive Fault", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x2, .event_descrip = "Predictive Failure", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x3, .event_descrip = "Hot Spare", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x4, .event_descrip = "Consistency Check/ Parity Check in Progress", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x5, .event_descrip = "In Critical Array", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x6, .event_descrip = "In Failed Array", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x7, .event_descrip = "Rebuild/Remap in progress", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Drive Slot", .type_code = 0xD, .specific_offset=0x8, .event_descrip = "Rebuild/Remap Aborted", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "POST Memory Resize", .type_code = 0xE, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x0, .event_data_2_descrip = "Unspecified"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x1, .event_data_2_descrip = "No System Memory installed"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x2, .event_data_2_descrip = "No usable system memory"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x3, .event_data_2_descrip = "Unrecoverable hard-disk/ATA/IDE device failure"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x4, .event_data_2_descrip = "Unrecoverable system-board failure"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x5, .event_data_2_descrip = "Unrecoverable diskette subsystem failure"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x6, .event_data_2_descrip = "Unrecoverable hard-disk controller failure"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x7, .event_data_2_descrip = "Unrecoverable PS/2 or USB Keyboard failure"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x8, .event_data_2_descrip = "Removable boot media not found"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x9, .event_data_2_descrip = "Unrecoverable video controller failure"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xA, .event_data_2_descrip = "No video device detected"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xB, .event_data_2_descrip = "Firmware (BIOS) ROM corruption detected"},
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xC, .event_data_2_descrip = "CPU voltage mismatch"},	
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x0, .event_descrip = "System Firmware Error (POST Error)", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xD, .event_data_2_descrip = "CPU speed matching failure"},		
	
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x0, .event_data_2_descrip = "Unspecified"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x1, .event_data_2_descrip = "Memory Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x2, .event_data_2_descrip = "Hard-disk Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x3, .event_data_2_descrip = "Secondary processor(s) Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x4, .event_data_2_descrip = "User authentication"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x5, .event_data_2_descrip = "User-initiated system setup"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x6, .event_data_2_descrip = "USB resource configuration "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x7, .event_data_2_descrip = "PCI resource configuration "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x8, .event_data_2_descrip = "Option ROM initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x9, .event_data_2_descrip = "Video Initialiation "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xA, .event_data_2_descrip = "Cache Initialization "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xB, .event_data_2_descrip = "SMBus Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xC, .event_data_2_descrip = "Keyboard Controller Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xD, .event_data_2_descrip = "Embedded Controller/Management Controller Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xE, .event_data_2_descrip = "Docking station attachment"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xF, .event_data_2_descrip = "Enablind Docking station "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x10, .event_data_2_descrip = "Docking station rejection"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x11, .event_data_2_descrip = "Disabling docking station"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x12, .event_data_2_descrip = "Calling operator system wake-up vector"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x13, .event_data_2_descrip = "Starting operating system boot process"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x14, .event_data_2_descrip = "Baseboard or motherboard Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x15, .event_data_2_descrip = "reserved"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x16, .event_data_2_descrip = "Floppy Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x17, .event_data_2_descrip = "Keyboard test"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x18, .event_data_2_descrip = "Pointing device test"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x1, .event_descrip = "System Firmware Hang", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x19, .event_data_2_descrip = "Primary processor Initialization"},			

	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x0, .event_data_2_descrip = "Unspecified"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x1, .event_data_2_descrip = "Memory Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x2, .event_data_2_descrip = "Hard-disk Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x3, .event_data_2_descrip = "Secondary processor(s) Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x4, .event_data_2_descrip = "User authentication"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x5, .event_data_2_descrip = "User-initiated system setup"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x6, .event_data_2_descrip = "USB resource configuration "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x7, .event_data_2_descrip = "PCI resource configuration "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x8, .event_data_2_descrip = "Option ROM initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x9, .event_data_2_descrip = "Video Initialisation "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xA, .event_data_2_descrip = "Cache Initialization "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xB, .event_data_2_descrip = "SMBus Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xC, .event_data_2_descrip = "Keyboard Controller Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xD, .event_data_2_descrip = "Embedded Controller/Management Controller Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xE, .event_data_2_descrip = "Docking station attachment"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0xF, .event_data_2_descrip = "Enabling Docking station "},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x10, .event_data_2_descrip = "Docking station rejection"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x11, .event_data_2_descrip = "Disabling docking station"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x12, .event_data_2_descrip = "Calling operator system wake-up vector"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x13, .event_data_2_descrip = "Starting operating system boot process"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x14, .event_data_2_descrip = "Baseboard or motherboard Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x15, .event_data_2_descrip = "reserved"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x16, .event_data_2_descrip = "Floppy Initialization"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x17, .event_data_2_descrip = "Keyboard test"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x18, .event_data_2_descrip = "Pointing device test"},		
	{.type = "System Firmware Progress", .type_code = 0xF, .specific_offset=0x2, .event_descrip = "System Firmware Progress", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x19, .event_data_2_descrip = "Primary processor Initialization"},			
	
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x0, .event_descrip = "Correctable Memory Error Logging Disabled", .event_data_2_flag=1, .event_data_3_flag=0, .event_data_2 = 0x0, .event_data_2_descrip = "Memory module/device"},		
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x1, .event_descrip = "Event Type Logging Disabled", .event_data_2_flag=1, .event_data_3_flag=1},
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x2, .event_descrip = "Log Area Reset/Cleared", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x3, .event_descrip = "All event Logging Disabled", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x4, .event_descrip = "SEL Full", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x5, .event_descrip = "SEL Almost Full", .event_data_2_flag=0, .event_data_3_flag=1},
	{.type = "Event Logging Disabled", .type_code = 0x10, .specific_offset=0x6, .event_descrip = "Correctable Machine Check Error Logging Disabled", .event_data_2_flag=1, .event_data_3_flag=1},
	
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x0, .event_descrip = "BIOS WatchDog Reset", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x1, .event_descrip = "OS WatchDog Reset", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x2, .event_descrip = "OS WatchDog Shut-down", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x3, .event_descrip = "OS WatchDog Power Down", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x4, .event_descrip = "OS WatchDog Power Cycle", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x5, .event_descrip = "OS WatchDog NMI/ Diagnostic Interrupt", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x6, .event_descrip = "OS WatchDog Expired, status only", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 1", .type_code = 0x11, .specific_offset=0x7, .event_descrip = "OS WatchDog pre-timeout interrupt, non-NMI", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x0, .event_descrip = "System Reconfigured", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x1, .event_descrip = "OEM System Boot Event", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x2, .event_descrip = "Undetermined system hardware failure", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x3, .event_descrip = "Entry Added to Auxillary Log", .event_data_2_flag=1, .event_data_3_flag=0},
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x4, .event_descrip = "PEF Action", .event_data_2_flag=1, .event_data_3_flag=0},
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x5, .event_descrip = "Timestamp Clock Synch", .event_data_2_flag=1, .event_data_3_flag=0},
	{.type = "System Event", .type_code = 0x12, .specific_offset=0x6, .event_descrip = "System Reconfigured", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x0, .event_descrip = "Front Panel NMI/ Diagnostic Interupt", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x1, .event_descrip = "Bus Timeout", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x2, .event_descrip = "I/O Channel Check NMI", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x3, .event_descrip = "Software NMI", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x4, .event_descrip = "PCI PERR", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x5, .event_descrip = "PCI SERR", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x6, .event_descrip = "EISA Fail Safe Timeout", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x7, .event_descrip = "Bus Correctable Error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x8, .event_descrip = "Bus Uncorrectable Error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0x9, .event_descrip = "Fatal NMI (port 61h, bit 7)", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0xA, .event_descrip = "Bus Fatal Error", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Critical Interrupt", .type_code = 0x13, .specific_offset=0xB, .event_descrip = "Bus Degraded (bus operating in a degraded performance state", .event_data_2_flag=0, .event_data_3_flag=0},

	{.type = "Button / Switch", .type_code = 0x14, .specific_offset=0x0, .event_descrip = "Power Button Pressed", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Button / Switch", .type_code = 0x14, .specific_offset=0x1, .event_descrip = "Sleep Button Pressed", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Button / Switch", .type_code = 0x14, .specific_offset=0x2, .event_descrip = "Reset Button Pressed", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Button / Switch", .type_code = 0x14, .specific_offset=0x3, .event_descrip = "FRU latch open", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Button / Switch", .type_code = 0x14, .specific_offset=0x4, .event_descrip = "FRU service request button", .event_data_2_flag=0, .event_data_3_flag=0},

	{.type = "Module/ Board", .type_code = 0x15, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},

	{.type = "Microcontroller/Coprocessor", .type_code = 0x16, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},

	{.type = "Add-in-card", .type_code = 0x17, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},

	{.type = "Chassis", .type_code = 0x18, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Chip Set", .type_code = 0x19, .specific_offset=0x0, .event_descrip = "Soft Power Control Failure", .event_data_2_flag=1, .event_data_3_flag=1},	
	{.type = "Chip Set", .type_code = 0x19, .specific_offset=0x1, .event_descrip = "Thermal Trip", .event_data_2_flag=0, .event_data_3_flag=0},	

	{.type = "Other FRU", .type_code = 0x1A, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},

	{.type = "Cable / Interconnect", .type_code = 0x1B, .specific_offset=0x0, .event_descrip = "Cable/ Interconnect is connected", .event_data_2_flag=1, .event_data_3_flag=1},	
	{.type = "Cable / Interconnect", .type_code = 0x1B, .specific_offset=0x1, .event_descrip = "Configuration Error - Incorrect cable connected / Incorrect interconnection", .event_data_2_flag=0, .event_data_3_flag=0},	
	
	{.type = "Terminator", .type_code = 0x1C, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},	
	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x0, .event_descrip = "Initiated by power up", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x1, .event_descrip = "Initiated by Hard Reset", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x2, .event_descrip = "Initiated by Warm Reset", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x3, .event_descrip = "User Requested PXE Boot", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x4, .event_descrip = "Automatic Boot to diagnostic", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x5, .event_descrip = "OS/ Run-time software initiated hard reset", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x6, .event_descrip = "OS/ Run-time software initiated warm reset", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "System Boot/Restart Initiated", .type_code = 0x1D, .specific_offset=0x7, .event_descrip = "System Restart", .event_data_2_flag=1, .event_data_3_flag=1},	
	
	{.type = "Boot Error", .type_code = 0x1E, .specific_offset=0x0, .event_descrip = "No Bootable media", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "Boot Error", .type_code = 0x1E, .specific_offset=0x1, .event_descrip = "Non-Bootable diskette left in drive", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "Boot Error", .type_code = 0x1E, .specific_offset=0x2, .event_descrip = "PXE Server not found", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "Boot Error", .type_code = 0x1E, .specific_offset=0x3, .event_descrip = "Invalid Boot Sector", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "Boot Error", .type_code = 0x1E, .specific_offset=0x4, .event_descrip = "Timeout waiting for user selection of boot source", .event_data_2_flag=0, .event_data_3_flag=0},	
	
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x0, .event_descrip = "A: boot completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x1, .event_descrip = "C: boot completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x2, .event_descrip = "PXE boot completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x3, .event_descrip = "Diagnostic boot completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x4, .event_descrip = "CD-ROM boot completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x5, .event_descrip = "ROM boot completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x6, .event_descrip = "boot completed - boot device not specified", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x7, .event_descrip = "Base OS/Hypervisor Installation Started", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x8, .event_descrip = "Base OS/Hypervisor Installation Completed", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0x9, .event_descrip = "Base OS/Hypervisor Installation  Aborted", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "Base OS Boot/ Installation Status", .type_code = 0x1F, .specific_offset=0xA, .event_descrip = "Base OS/Hypervisor Installation  Failed", .event_data_2_flag=0, .event_data_3_flag=0},		
	
	{.type = "OS Stop/Shutdown", .type_code = 0x20, .specific_offset=0x0, .event_descrip = "Critical stop during OS load / initialization", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "OS Stop/Shutdown", .type_code = 0x20, .specific_offset=0x1, .event_descrip = "Run-time Critical stop ", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "OS Stop/Shutdown", .type_code = 0x20, .specific_offset=0x2, .event_descrip = "OS Graceful Stop", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "OS Stop/Shutdown", .type_code = 0x20, .specific_offset=0x3, .event_descrip = "OS Graceful Shutdown", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "OS Stop/Shutdown", .type_code = 0x20, .specific_offset=0x4, .event_descrip = "Soft Shutdown initiated by PEF", .event_data_2_flag=0, .event_data_3_flag=0},		
	{.type = "OS Stop/Shutdown", .type_code = 0x20, .specific_offset=0x5, .event_descrip = "Agent Not Responding", .event_data_2_flag=0, .event_data_3_flag=0},		
	
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x0, .event_descrip = "Fault Status Asserted", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x1, .event_descrip = "Identify Status Asserted", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x2, .event_descrip = "Slot / Connector Device Installed/ attached", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x3, .event_descrip = "Slot / Connector Ready for Device Installation", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x4, .event_descrip = "Slot / Connector Ready for Device Removal", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x5, .event_descrip = "Slot Power is Off", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x6, .event_descrip = "Slot / Connector Device Removal Request", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x7, .event_descrip = "Interlock Asserted", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x8, .event_descrip = "Slot is disabled", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Slot / Connector", .type_code = 0x21, .specific_offset=0x9, .event_descrip = "Slot holds spare device", .event_data_2_flag=1, .event_data_3_flag=1},
	
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x0, .event_descrip = "S0 / G0 Working", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x1, .event_descrip = "S1 sleeping with system h/w & processor contexct maintained", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x2, .event_descrip = "S2 sleeping, processor context lost", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x3, .event_descrip = "S3 sleeping, processor & h/w context lost, memory retained", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x4, .event_descrip = "S4 non-volatile sleep/ suspend-to-disk", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x5, .event_descrip = "S5 / G2 soft-off", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x6, .event_descrip = "S4 / S5  soft-off", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x7, .event_descrip = "G3 / Mechanical Off", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x8, .event_descrip = "Sleeping in an S1, S2 or S3 states", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0x9, .event_descrip = "G1 sleeping", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0xA, .event_descrip = "S5 entered by override", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0xB, .event_descrip = "Legacy ON State", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0xC, .event_descrip = "Legacy OFF State", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "System ACPI Power State", .type_code = 0x22, .specific_offset=0xE, .event_descrip = "Unknown", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "WatchDog 2", .type_code = 0x23, .specific_offset=0x0, .event_descrip = "Timer Expired, Status Only ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 2", .type_code = 0x23, .specific_offset=0x1, .event_descrip = "Hard Reset ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 2", .type_code = 0x23, .specific_offset=0x2, .event_descrip = "Power Down ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 2", .type_code = 0x23, .specific_offset=0x3, .event_descrip = "Power Cycle ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "WatchDog 2", .type_code = 0x23, .specific_offset=0x8, .event_descrip = "Timer interrupt ", .event_data_2_flag=1, .event_data_3_flag=0},
	
	{.type = "Platform Alert", .type_code = 0x24, .specific_offset=0x0, .event_descrip = "Platform generated Page ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Alert", .type_code = 0x24, .specific_offset=0x1, .event_descrip = "Platform generated LAN Alert ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Alert", .type_code = 0x24, .specific_offset=0x2, .event_descrip = "Platform Event Trap generated ", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Platform Alert", .type_code = 0x24, .specific_offset=0x3, .event_descrip = "Platform generated SNMP trap, OEM format ", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Entity Presence", .type_code = 0x25, .specific_offset=0x0, .event_descrip = "Entity Present ", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "Entity Presence", .type_code = 0x25, .specific_offset=0x1, .event_descrip = "Entity Absent ", .event_data_2_flag=0, .event_data_3_flag=0},	
	{.type = "Entity Presence", .type_code = 0x25, .specific_offset=0x2, .event_descrip = "Entity Disabled ", .event_data_2_flag=0, .event_data_3_flag=0},	

	{.type = "Monitor ASIC / IC", .type_code = 0x26, .specific_offset=0x0, .event_descrip = "", .event_data_2_flag=0, .event_data_3_flag=0},	
	
	{.type = "LAN", .type_code = 0x27, .specific_offset=0x0, .event_descrip = "LAN Heartbeat Lost", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "LAN", .type_code = 0x27, .specific_offset=0x1, .event_descrip = "LAN Heartbeat", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Management Subsystem Health", .type_code = 0x28, .specific_offset=0x0, .event_descrip = "Sensor access degraded or unavailable", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Management Subsystem Health", .type_code = 0x28, .specific_offset=0x1, .event_descrip = "Controller access degraded or unavailable", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Management Subsystem Health", .type_code = 0x28, .specific_offset=0x2, .event_descrip = "Management Controller off-line", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Management Subsystem Health", .type_code = 0x28, .specific_offset=0x3, .event_descrip = "Management Controller not available", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Management Subsystem Health", .type_code = 0x28, .specific_offset=0x4, .event_descrip = "Sensor failure", .event_data_2_flag=1, .event_data_3_flag=0},
	{.type = "Management Subsystem Health", .type_code = 0x28, .specific_offset=0x5, .event_descrip = "FRU failure", .event_data_2_flag=1, .event_data_3_flag=1},
	
	{.type = "Battery", .type_code = 0x29, .specific_offset=0x0, .event_descrip = "Battery Low (Predictive Failure)", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Battery", .type_code = 0x29, .specific_offset=0x1, .event_descrip = "Battery Failed", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Battery", .type_code = 0x29, .specific_offset=0x2, .event_descrip = "Battery Presence Detected", .event_data_2_flag=0, .event_data_3_flag=0},
	
	{.type = "Session Audit", .type_code = 0x2A, .specific_offset=0x0, .event_descrip = "Session Activated", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Session Audit", .type_code = 0x2A, .specific_offset=0x1, .event_descrip = "Session Deactivated", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Session Audit", .type_code = 0x2A, .specific_offset=0x2, .event_descrip = "Invalid Username or Password", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Session Audit", .type_code = 0x2A, .specific_offset=0x3, .event_descrip = "Invalid password disable", .event_data_2_flag=1, .event_data_3_flag=1},
	
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x0, .event_descrip = "Hardware change detected with associated Entity", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x1, .event_descrip = "Firmware or software change detected with associated Entity", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x2, .event_descrip = "Hardware incompatibility detected with associated Entity", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x3, .event_descrip = "Firmware or software incompatibility detected with associated Entity", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x4, .event_descrip = "Entity is of an invalid or unsupported hardware version", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x5, .event_descrip = "Entity contains an invalid or unsupported firmware or software version", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x6, .event_descrip = "Hardware change detected with associated Entity was successful", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x0,  event_data_2_descrip="Unspecified"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x1,  event_data_2_descrip="Management Controller devide ID"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x2,  event_data_2_descrip="Management Controller firmware revision"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x3,  event_data_2_descrip="Management Controller device revision"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x4,  event_data_2_descrip="Management Controller manufacturer ID"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x5,  event_data_2_descrip="Management Controller IPMI version"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x6,  event_data_2_descrip="Management Controller Auxillary Firtmware ID"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x7,  event_data_2_descrip="Management Controller firmware boot block"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x8,  event_data_2_descrip="other management controller firmware"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x9,  event_data_2_descrip="System firmware (EFI/BIOS) change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0xA,  event_data_2_descrip="SMBIOS Change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0xB,  event_data_2_descrip="Operating System Change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0xC,  event_data_2_descrip="Operating System Loader Change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0xD,  event_data_2_descrip="Service or Diagnostic Partition change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0xE,  event_data_2_descrip="Management Software agent change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0xF,  event_data_2_descrip="Management Software application change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x10,  event_data_2_descrip="Management Software middleware change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x11,  event_data_2_descrip="Programmable hardware change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x12,  event_data_2_descrip="Board/FRU module change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x13,  event_data_2_descrip="Board/FRU component change"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x14,  event_data_2_descrip="Board/FRU replaced with equivalent version"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x15,  event_data_2_descrip="Board/FRU replaced with newer version"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x16,  event_data_2_descrip="Board/FRU replaced with older version"},
	{.type = "Version Change", .type_code = 0x2B, .specific_offset=0x7, .event_descrip = "Software or firmware change detected with associated Entity was successful", .event_data_2_flag=1, .event_data_3_flag=0, event_data_2=0x17,  event_data_2_descrip="Board/FRU hardware configuration change"},
	
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x0, .event_descrip = "FRU Not Installed", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x1, .event_descrip = "FRU Inactive", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x2, .event_descrip = "FRU Activation Requested", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x3, .event_descrip = "FRU Activation In Progress", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x4, .event_descrip = "FRU Active", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x5, .event_descrip = "FRU Deactivation Requested", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x6, .event_descrip = "FRU Deactivation In Progress", .event_data_2_flag=0, .event_data_3_flag=0},
	{.type = "FRU State", .type_code = 0x2C, .specific_offset=0x7, .event_descrip = "FRU Communication Lost", .event_data_2_flag=1, .event_data_3_flag=0},
};
	
	
	
	
	
	