struct ipmi_entity_id_codes {
	uint8_t entity_id;
	char entity[32];
};

struct ipmi_entity_id_codes g_ipmi_entity_id_codes[] = {
	{.entity_id=0x00h, .entity_name="unspecified"},
	{.entity_id=0x01h, .entity_name="other"},
	{.entity_id=0x02h, .entity_name="unknown"}, 
	{.entity_id=0x03h, .entity_name="processor"},
	{.entity_id=0x04h, .entity_name="disk or disk bay"},
	{.entity_id=0x05h, .entity_name="peripheral bay"},
	{.entity_id=0x06h, .entity_name="system management module"},
	{.entity_id=0x07h, .entity_name="system board"}, 
	{.entity_id=0x08h, .entity_name="memory module"}, 
	{.entity_id=0x09h, .entity_name="processor module"}, 
	{.entity_id=0x0Ah, .entity_name="power supply "},
	{.entity_id=0x0Bh, .entity_name="add-in card"},
	{.entity_id=0x0Ch, .entity_name="front panel board "},
	{.entity_id=0x0Dh, .entity_name="back panel board"},
	{.entity_id=0x0Eh, .entity_name="power system board"},
	{.entity_id=0x0Fh, .entity_name="drive backplane"},
	{.entity_id=0x10h, .entity_name="system internal expansion board "},
	{.entity_id=0x11h, .entity_name="Other system board (part of board set)"},
	{.entity_id=0x12h, .entity_name="processor board"}, 
	{.entity_id=0x13h, .entity_name="power unit / power domain "},
	{.entity_id=0x14h, .entity_name="power module / DC-to-DC converter "},
	{.entity_id=0x15h, .entity_name="power management / power distribution board"},
	{.entity_id=0x16h, .entity_name="chassis back panel board"},
	{.entity_id=0x17h, .entity_name="system chassis"},
	{.entity_id=0x18h, .entity_name="sub-chassis"},
	{.entity_id=0x19h, .entity_name="Other chassis board"},
	{.entity_id=0x1Ah, .entity_name="Disk Drive Bay"},
	{.entity_id=0x1Bh, .entity_name="Peripheral Bay"},
	{.entity_id=0x1Ch, .entity_name="Device Bay"},
	{.entity_id=0x1Dh, .entity_name="fan / cooling device"},
	{.entity_id=0x1Eh, .entity_name="cooling unit / cooling domain "},
	{.entity_id=0x1Fh, .entity_name="cable / interconnect"},
	{.entity_id=0x20h, .entity_name="memory device "},
	{.entity_id=0x21h, .entity_name="System Management Software"},
	{.entity_id=0x22h, .entity_name="System Firmware (e.g. BIOS / EFI)"},
	{.entity_id=0x23h, .entity_name="Operating System"},
	{.entity_id=0x24h, .entity_name="system bus"},
	{.entity_id=0x25h, .entity_name="Group "},
	{.entity_id=0x26h, .entity_name="Remote (Out of Band) Management Communication Device"},
	{.entity_id=0x27h, .entity_name="External Environment "},
	{.entity_id=0x28h, .entity_name="battery"},
	{.entity_id=0x29h, .entity_name="Processing blade "},
	{.entity_id=0x2Ah, .entity_name="Connectivity switch "},
	{.entity_id=0x2Bh, .entity_name="Processor/memory module "},
	{.entity_id=0x2Ch, .entity_name="I/O module "},
	{.entity_id=0x2Dh, .entity_name="Processor/ IO module "},
	{.entity_id=0x2Eh, .entity_name="Management Controller Firmware "},
	{.entity_id=0x2Fh, .entity_name="IPMI Channel "},
	{.entity_id=0x30h, .entity_name="PCI Bus"},
	{.entity_id=0x31h, .entity_name="PCI Express™ Bus"},
	{.entity_id=0x32h, .entity_name="SCSI Bus (parallel)"},
	{.entity_id=0x33h, .entity_name="SATA / SAS bus"},
	{.entity_id=0x34h, .entity_name="Processor / front-side bus"},
	{.entity_id=0x35h, .entity_name="Real Time Clock (RTC)"},
	{.entity_id=0x37h, .entity_name="air inlet "},
	{.entity_id=0x40h, .entity_name="air inlet (Interoperatability with DCMI 1.0 specifications) "},
	{.entity_id=0x41h, .entity_name="processor / CPU (Interoperability with the DCMI 1.0 specifications) "},
	{.entity_id=0x42h, .entity_name="baseboard / main system board (Interoperability with the DCMI 1.0 specifications) "},
};